
export const UPDATE_NUMBER_REQUEST = 'number/UPDATE_NUMBER_REQUEST';
export const UPDATE_NUMBER_SUCCESS = 'number/UPDATE_NUMBER_SUCCESS';
export const UPDATE_NUMBER_FAILURE = 'number/UPDATE_NUMBER_REQUEST';

export const INCREMENT_NUMBER = 'number/INCREMENT_NUMBER';
export const DECREMENT_NUMBER = 'number/DECREMENT_NUMBER';