
export const GET_POKEMON_BY_NAME = 'number/GET_POKEMON_BY_NAME';
export const GET_POKEMON_BY_NAME_SUCCESS = 'number/GET_POKEMON_BY_NAME_SUCCESS';
export const GET_POKEMON_BY_NAME_FAILURE = 'number/GET_POKEMON_BY_NAME_FAILURE';
